## 03 - Pitt dataset cleaning
In this notebook, we will try to detect overlaps between Pitt dataset and our train / test dataset

In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer, util

In [2]:
# load Pitt dataset

# src_fname = "../data/splits/train_50pc.csv"
src_fname = "../data/splits/train_pitt.csv"

src_df = pd.read_csv(src_fname)
src_df.head()

  file_id                                               text target
0   001-0  mhm .\nalright .\nthere's &-um a young boy tha...     AD
1   001-2  mhm .\nthere's a young boy &-uh going in a coo...     AD
2   003-0  here's a cookie jar .\nand the lid is off the ...     AD
3   005-0  the boy is slipping off the stool .\nhe's tryi...     AD
4   005-2  okay ‡ he's fallin(g) off a chair  .\nshe's &-...     AD

In [3]:
# load original test set
# tgt_fname = "../data/splits/train_pitt.csv"
tgt_fname = "../data/splits/test_text.csv"
# tgt_fname = "../data/splits/train_50pc.csv"

tgt_df = pd.read_csv(tgt_fname)
tgt_df.head()

         ID  Prediction                                               text
0  adrsdt15         NaN  I see oh boy, almost falling on a stool trying...
1  adrsdt40         NaN  Well the kids are trying to get the cookies an...
2  adrsdt26         NaN  Okay, this is a family setting in a kitchen an...
3  adrsdt67         NaN  Oh, what do I see in this picture? This remind...
4  adrsdt58         NaN  While the young boy is reaching for a cookie j...

In [16]:
# get a random item from src dataset
import random
# k = random.randint(0, len(src_df))
k = 184
print(k)
src_item = src_df.iloc[k]
src_item["text"]

184

"mhm .\noh .\nthere's a cookie jar .\nand the boy is toppling off (.) a stool .\nand the mother is spilling the water .\nand the\n(..) that's about it ."

In [17]:
# calculate embeddings
# model = SentenceTransformer("all-distilroberta-v1")
# model = SentenceTransformer("all-mpnet-base-v2")
# model = SentenceTransformer("sentence-T5-large")
model = SentenceTransformer("all-roberta-large-v1") # the same model as in hybrid approach
s = "Hello world"
v = model.encode(s)
print(v.shape)

(1024,)

In [18]:
# apply to src item
src_v = model.encode(src_item["text"])
print(src_v.shape)

(1024,)

In [19]:
# apply embeddings to target df
print("Calculating target embeddings...")
tgt_vecs = model.encode(tgt_df["text"])
print("Completed")
print(tgt_vecs.shape)

Calculating target embeddings...
Completed
(71, 1024)

In [21]:
def compare(src_v, tgt_vecs, threshold=0.85, quiet=True):
    """
        compare source vector (1 vector) with a list of target vectors
        return the index of most similar vector
    """
    # result = []
    result = None
    max_score = 0
    max_id = None
    
    for i, v in enumerate(tgt_vecs):
        score = util.cos_sim(v, src_v).item()
        if not quiet:
            print("Score =", score)
        if  score >= threshold and score > max_score:
            print("New high similarity detected. Index =", i)
            # result.append(i)
            max_score = score
            max_id = i
    
    
    # return result
    return max_id

result = compare(src_v, tgt_vecs, threshold=0.6, quiet=False)
# print("Counts =", len(result))
print(result)

Score = 0.6053565740585327
New high similarity detected. Index = 0
Score = 0.5803213715553284
Score = 0.460700660943985
Score = 0.32941585779190063
Score = 0.5687123537063599
Score = 0.3492952585220337
Score = 0.4630916714668274
Score = 0.4525010585784912
Score = 0.5858467221260071
Score = 0.43810001015663147
Score = 0.6144494414329529
New high similarity detected. Index = 10
Score = 0.6501197218894958
New high similarity detected. Index = 11
Score = 0.6110761165618896
Score = 0.38539186120033264
Score = 0.37243109941482544
Score = 0.4850243926048279
Score = 0.5340250134468079
Score = 0.4943351447582245
Score = 0.5243884921073914
Score = 0.5144447684288025
Score = 0.5652144551277161
Score = 0.6651232242584229
New high similarity detected. Index = 21
Score = 0.49976399540901184
Score = 0.598824143409729
Score = 0.5675228238105774
Score = 0.5264087915420532
Score = 0.5760680437088013
Score = 0.5629412531852722
Score = 0.5771655440330505
Score = 0.5891528725624084
Score = 0.4775978624820709
Score = 0.5199945569038391
Score = 0.6439858675003052
Score = 0.42280417680740356
Score = 0.5448430776596069
Score = 0.6206614971160889
Score = 0.6125844120979309
Score = 0.4777624011039734
Score = 0.6536034345626831
Score = 0.4314163327217102
Score = 0.5512028336524963
Score = 0.6170658469200134
Score = 0.47927844524383545
Score = 0.5708986520767212
Score = 0.4753950238227844
Score = 0.517622172832489
Score = 0.6414146423339844
Score = 0.5570449829101562
Score = 0.5915411710739136
Score = 0.5448868870735168
Score = 0.5784446597099304
Score = 0.5982924103736877
Score = 0.5093802213668823
Score = 0.5570427775382996
Score = 0.3879387378692627
Score = 0.6343713402748108
Score = 0.350475013256073
Score = 0.5440496206283569
Score = 0.6670647859573364
New high similarity detected. Index = 58
Score = 0.4241337776184082
Score = 0.6055735945701599
Score = 0.5656161308288574
Score = 0.610175609588623
Score = 0.5938228368759155
Score = 0.552642822265625
Score = 0.5656895041465759
Score = 0.4972904324531555
Score = 0.6421358585357666
Score = 0.7143731117248535
New high similarity detected. Index = 68
Score = 0.426926851272583
Score = 0.5197020173072815
68

In [9]:
# ### Now we can do pair-wise checking
# ID_field = "file_id" # set to ID for original test set

# result = []
# for i in range(len(src_df)):
#     print("Checking item =", i)
#     item = src_df.iloc[i]
#     src_text = item["text"]
#     src_v = model.encode(src_text)
#     sim_id = compare(src_v, tgt_vecs, threshold=0.95)
#     # if len(sim_id) > 0:
#     if sim_id is not None:
#         print("High similarity detected")
#         src_file_id = item[ID_field]
#         print(f"Src id = {i}, file_id = [{src_file_id}], \ntext = [{src_text}]")
#         print(f"Similar ids = {sim_id}")
#         for j in sim_id:
#             tgt_text = tgt_df.iloc[j]["text"]
#             tgt_file_id = tgt_df.iloc[j]["file_id"]
#             print("Target text =", tgt_text)
#             print("-------")
#             result.append((src_text, tgt_text, src_file_id, tgt_file_id))

In [35]:
### Now we can do pair-wise checking
# ID_field = "file_id" # set to ID for original test set
src_ID_field = "file_id" # set to ID for original test set
tgt_TD_field = "ID"
threshold = 0.75

result = []
for i in range(len(src_df)):
    print("Checking item =", i)
    item = src_df.iloc[i]
    src_text = item["text"]
    src_v = model.encode(src_text)
    sim_id = compare(src_v, tgt_vecs, threshold=threshold)
    # if len(sim_id) > 0:
    if sim_id is not None:
        print("High similarity detected")
        src_file_id = item[src_ID_field]
        print(f"Src id = {i}, file_id = [{src_file_id}], \ntext = [{src_text}]")
        print(f"Similar ids = {sim_id}")
        # for j in sim_id:
        print("--------")
        tgt_text = tgt_df.iloc[sim_id]["text"]
        tgt_file_id = tgt_df.iloc[sim_id][tgt_TD_field]
        print("Target text =", tgt_text)
        print("-------")
        result.append((src_text, tgt_text, src_file_id, tgt_file_id))

Checking item = 0
Checking item = 1
Checking item = 2
Checking item = 3
Checking item = 4
Checking item = 5
Checking item = 6
Checking item = 7
Checking item = 8
Checking item = 9
Checking item = 10
Checking item = 11
Checking item = 12
Checking item = 13
Checking item = 14
Checking item = 15
Checking item = 16
Checking item = 17
Checking item = 18
Checking item = 19
Checking item = 20
Checking item = 21
Checking item = 22
Checking item = 23
New high similarity detected. Index = 38
High similarity detected
Src id = 23, file_id = [029-1],
text = [alright .
I see the little boy stealing cookies from the cookie jar .
and <the little girl's>  &-uh he gave some to the little girl .
and she's eatin(g) some of the cookies .
and I guess this is mama .
and she's washing the dishes .
and she dropped a dish .
no  no ‡ she didn't drop a dish .
uh the  the water that she's washing the dishes with she let
and it's overflown  &=laughs &+o &+o overflown .
that doesn't>
did &*INV:no it &-uh +/?
we forgot to turn off the spigot .
and so the water is running off <into the>  onto the floor here
and mom apparently is washing the dishes .
and here's this little boy stealing <the cookie>  the cookies .
he's gonna>  <the
and mama's drying the dishes as usual for mamas (.) if they don't
uh let's see now .
I guess there's more things I'm sposta see .
let's see here now .
oh ‡ &-uh (.) and the  the water is &-uh flowing out <of the>
mom apparently here, she forgot to turn off the water .
and the  &+f <onto the
and the little girl has pushed over the (.) chair
uh I  she pushed it over
you_know it &-uh I  I]
Similar ids = 38
--------
Target text = All right, tell me what you see going on in that picture. I see the little boy stealing cookies from the cookie jar. And the little girls and he gave some to the little girl and she's eat some of the cookies. And I guess this is mama and she's washing the dishes. And she dropped a dish. No, no, she didn't drop it. They shared the water that she's washing the dishes with she left run. And it's overflowing. Overflowing it didn't that didn't sound right did we forgot to turn off the spigot. And so the water is running off into the onto the floor here. And mom apparently is washing the dishes. And here's this little boy stealing the cookie cookies. He's gonna He's gonna fall because he's cooking her or the bench these four legged stool whatever it is gonna fall over. And the cookie jar. Mama's drying dishes jewel for mamas. They don't have a husband that drives them or watches him or whatever. Let's see. I guess there's more things that I'm supposed to see. You tell me when you finished Sr. Oh. And the water is flowing out of the sink and they've got the turn off whoever's doing the dishwashing, mom up. Turn off the water. The water is spilling out over onto the floor of the kitchen floor. Girl was pushed over the chair



was the boy that he was reaching up and get the cookies. Either he she pushed it over you know? Excuse me. But you know I was

-------
Checking item = 24
New high similarity detected. Index = 61
New high similarity detected. Index = 66
High similarity detected
Src id = 24, file_id = [030-0],
text = [it's a picture of a kitchen .
there's a child reaching on  a cookie jar .
um <a male>
he's falling .
the stool is falling .
uh his  a female youngster maybe sister is
and she's got a finger to her lip .
the &-uh mother is at the sink washing a dish .
the water is spilling over from the sink .
the window is open looking out onto &-uh shrubbery and a path to
there are two  three dishes sitting
and there are a number of &-uh cabinets &-uh in the picture &-uh on
and there's the &-uh cabinets above where the boy is reaching in .
mother is washing a dish .
she is dressed in a &-um oh &+d dress .
and it appears she has an apron and a towel in her hand .
as she's washing she's  one of her feet is &-uh obviously in
the children are wearing  &-um completely outfitted .
the girl with &-uh sandals of some kind and the boy it looks like]
Similar ids = 66
--------
Target text = cute pictures in in a kitchen with a family. Mother and son and daughter and the son is up in the cookie jar. The cupboard doors open he's getting cookies in the jar. He's standing on a stool which is in the process of toppling over the little girls holding her hand for a cookie and she's also has her finger to her lips shushing him so he doesn't make any noise. The mothers seem to live up to what's going on. She's standing there wiping dish and tap water running the sink is overflowing down on the floor and she's standing in a puddle look outside and the curtains are open and see what looks like could be a graduated extension of the house shrubbery path tree going back in the kitchen on the counter beside her is another plate and cream and sugar was set



the little boy's shoes he looks like he has jogging shoes on and low socks and he's he's wearing shorts and a short sleeve shirt. His sister's wearing what amounts to sort of a mini dress mini skirt with sandals and I'll see her ruffled ruffled curtains at the at the windows are drawn back by draw drapes and the cupboards all have recessed handles or no they're not recessed, they first glance are recessed but actually they protrude out from the doors and also copyright 1972 Thank you

-------
Checking item = 25
Checking item = 26
Checking item = 27
Checking item = 28
Checking item = 29
Checking item = 30
Checking item = 31
Checking item = 32
Checking item = 33
Checking item = 34
Checking item = 35
Checking item = 36
Checking item = 37
New high similarity detected. Index = 39
High similarity detected
Src id = 37, file_id = [049-0],
text = [=clears:throat you want me to tell you ?
um the girl is talking to the boy .
he's getting the cookie jar down .
he has a &+coo cookie in his hand .
uh he's falling off of his stool .
the mother's doing the dishes and the water's running off into the
she's looking out the window apparently .
um I see grass and a lawn at  outside .
and I see two bowls, cabinets .
anything else I xxx ?
you want everything I can see ?
I also see a cabinet drawer  door there .
remember I said the water was overflowing +/.
oh .
xxx .
there's something inside here .
okay .]
Similar ids = 39
--------
Target text = There's a picture. Let me tell you just tell me everything that you see.



Girls talking to the boy he's getting a cookie jar down. He has a coffee in his hand. He's falling off his stool. Mothers do the dishes and the water is running off into the floor. She's looking out the window apparently. I see grass and lawn outside. And I see two bowls. Cabinets. Anything else? You want everything I can also see a cabinet door there.



What's happening over here?



Remember I said the water was overflowing?



Yeah, sorry. Instead of layer on that. Do you know sometimes the light glass that's fine.



There's nothing inside here.



It's only the major things. That's fine. Okay.

-------
Checking item = 38
Checking item = 39
Checking item = 40
Checking item = 41
Checking item = 42
Checking item = 43
Checking item = 44
Checking item = 45
Checking item = 46
Checking item = 47
Checking item = 48
Checking item = 49
New high similarity detected. Index = 55
High similarity detected
Src id = 49, file_id = [058-1],
text = [okay I'll start .
the mother is drying dishes .
and the sink is over flowing .
the water is falling onto the floor .
uh the boy is on his stool &-uh taking cookies out_of a cookie
and he has <one cookie>  two cookies one in each hand .
the &-uh girl is standing, reaching up for a cookie with her &-uh
the stool is on one leg .
uh there's drapes on the window .
there's a path &-uh between the grass and the bushes .
and this little picture is a part of the xxx house and part of the
there are &-uh &-uh doors on the &-uh cabinets in the sink .
and &-uh it's daylight .
um there's two cups and a dish <on it>  on the sink .
=hums (..) should I describe the two faucets ?]
Similar ids = 55
--------
Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitting on the countertop



cupboards



lady has a Fernand dress slippers boy has a short sleeve shirt, short pants



socks shoes her eyes on. dress socks special person



saying fossa with water banana



and open window



curtains

-------
Checking item = 50
Checking item = 51
Checking item = 52
Checking item = 53
Checking item = 54
Checking item = 55
Checking item = 56
Checking item = 57
Checking item = 58
Checking item = 59
Checking item = 60
Checking item = 61
Checking item = 62
Checking item = 63
Checking item = 64
Checking item = 65
Checking item = 66
Checking item = 67
Checking item = 68
Checking item = 69
Checking item = 70
Checking item = 71
Checking item = 72
Checking item = 73
Checking item = 74
Checking item = 75
Checking item = 76
Checking item = 77
Checking item = 78
Checking item = 79
Checking item = 80
Checking item = 81
Checking item = 82
Checking item = 83
Checking item = 84
Checking item = 85
Checking item = 86
Checking item = 87
Checking item = 88
Checking item = 89
Checking item = 90
Checking item = 91
Checking item = 92
Checking item = 93
Checking item = 94
Checking item = 95
Checking item = 96
Checking item = 97
Checking item = 98
Checking item = 99
Checking item = 100
Checking item = 101
Checking item = 102
Checking item = 103
Checking item = 104
Checking item = 105
Checking item = 106
Checking item = 107
Checking item = 108
Checking item = 109
Checking item = 110
Checking item = 111
Checking item = 112
Checking item = 113
Checking item = 114
Checking item = 115
Checking item = 116
Checking item = 117
New high similarity detected. Index = 43
High similarity detected
Src id = 117, file_id = [184-1],
text = [okay, I see a boy in the cookie jar .
I see he has the lid off .
I see that he is standing on a three legged stool and he's about to
he has one cookie in his hand, handin(g) it down to his sister and
and I think she's indicating to the boy to keep still so his mother
I see the mother .
uh I guess she's drying the dishes and she's not paying attention
and she must not be conscious because she's standing in it and
um &+sh <I think she must>  I think she's probably lookin(g)
and I see apparently a couple dirty dishes on the tabletop .
I see the cupboards .
uh I don't know whether they all have knobs on them or not .
doesn't look like the two where the boy and the girl are have knobs
and I see outside .
I see &-uh apparently it's a tree, some shrubbery and some hedges .
about it ?]
Similar ids = 43
--------
Target text = All of the action Okay, I see a boy in a cookie jar as he has a bit off. See, he is standing on a three legged stool and he's about to depart from the two legged stool as one cookies handed down to his sister and she's reaching out for it and I think she's indicating diverting to steal sighs mother



I see my mother I guess she's drying the dishes she's not paying attention because she's leaving the sink run over spilling all over the floor she must not be conscious because she's standing doesn't know



I think she missed me. I think she's probably looking at the windows I take the second and I see we're very judicious people can't I see my cupboards weather they all have no it doesn't look like a two door and I see outside I see a tree from slippery edges OKAY. OKAY.

-------
Checking item = 118
Checking item = 119
Checking item = 120
Checking item = 121
Checking item = 122
New high similarity detected. Index = 11
High similarity detected
Src id = 122, file_id = [206-0],
text = [well ‡ the mother is drying the plate .
uh the water is running on the floor &+overru overrunning in the
the kids are &+s taking cookies from the cookie jar .
and <on a>
and the girl is receiving the cookies .
the sister „ I suppose .
the little girl .
the little boy is takin(g) the cookies .
and <the little girl is>  he's handing them to her .
and I'd be there eating them too (be)cause I like cookies .
I'd be a>
and the mother is drying the dishes at the sink .
the water's running over .
*INV:okay xxx and she's not paying any never minds to it „ I guess
=laughs the floor's getting wet .
she'll hafta &*INV:she_doesn't_care_yeah get a mop and mop it up !
oh this &*INV:how_about_over_here is crazy .
well ‡ <the chair  &-uh the kid's
and he's going to land on his rear end pretty soon .
those might be a couple cookies in his hand .
probably the cookie jar spilled too .
he might catch that &*INV:hm when it went to the floor „ yeah .
that's about all .
*INV:okay the sink is running over .
the water's <on the>  dripping on the floor, all over the floor
the old lady (w)ill hafta get a mop and mop up the floor too after]
Similar ids = 11
--------
Target text = What do you see going on infection mother's drying flight or the waters running or running in the Safe Kids taking cookies from the cookie jar and I share that with you know three chests in the cupboard and the girl is receiving the cookies is this guy suppose the little girl and boy is taking the cookies in the room the handing them tour and that be they're eating the foods that I like cookies



as the other hand is always in the cookie and the mother's drying the dishes at the same time the waters running over each and she's not paying any nevermind to it I guess the floors getting washed your left



ever hear anything else going on over here? Well, the chairs the kids going to fall from the stool the high stool and stomping over and he's going to land on his rear end. Pretty soon. It may be a couple of cookies in the same problem the cookie jar still to eat my kitchen. What to look for. Yeah, okay. It's about Oh, okay. It's running over the water zone and dripping on the floor all over the floor the O A O F to get a mop and mop the floor.

-------
Checking item = 123
Checking item = 124
Checking item = 125
Checking item = 126
New high similarity detected. Index = 55
High similarity detected
Src id = 126, file_id = [212-2],
text = [yeah, alright .
the girl is reaching up for a cookie .
the youngster's getting the cookie out_of the cupboard .
the cookie is in the pan
the &-uh bench  the stool that he's
the door to the cookie cupboard is open .
the lady is washing dishes .
she has a dish cloth in her hand .
the &-uh sink is runnin(g) over .
the spigot is &-um not shut off .
there's two handles and neither one is shut off .
there's  &-um and it's fallin(g) on the floor .
the
there's curtains .
there's &-uh two windows .
at least there's a window with two &-uh panes showing, partial the
and it looks like a scenery outside like a  a walk and some
and some bushes in front of the  (.) some kind of a building .
she has on an apron, (.) shoes .
and <the child>  the young girl has shoes and stockings on and
and &-uh (.) the cabinet has two  two three four five doors to]
Similar ids = 55
--------
Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitting on the countertop



cupboards



lady has a Fernand dress slippers boy has a short sleeve shirt, short pants



socks shoes her eyes on. dress socks special person



saying fossa with water banana



and open window



curtains

-------
Checking item = 127
Checking item = 128
Checking item = 129
Checking item = 130
Checking item = 131
Checking item = 132
Checking item = 133
Checking item = 134
Checking item = 135
Checking item = 136
Checking item = 137
Checking item = 138
Checking item = 139
Checking item = 140
New high similarity detected. Index = 1
New high similarity detected. Index = 46
New high similarity detected. Index = 68
High similarity detected
Src id = 140, file_id = [221-3],
text = [well ‡ the boy is taking cookies out_o(f) the cookie jar .
and he's handing one to his sister as he almost falls off his stool
and he has knocked the lid off the cookie jar .
and the mother is washing dishes .
and she has let the sink overflow .
and she's standing in a puddle .
and &+d window is open .
and &-uh there's a view of the back of the house with a hedge and a
and the curtains are blowing in the wind .
and she's standing in a puddle .
and so that's about all .]
Similar ids = 68
--------
Target text = This boy is about to fall off the stool. The mother is washing dishes and the water spilling over on the kitchen floor. The wind is blowing the curtains. The little girl was laughing and her brother who's taking a cookie out of the cookie jar

-------
Checking item = 141
Checking item = 142
New high similarity detected. Index = 44
High similarity detected
Src id = 142, file_id = [222-1],
text = [all the action ?
(.) okay ‡ it's a boy and a girl (.) and their mom .
(.) and
(..) and then this here when the  it should
it's goin(g) all the way down in there .
um they're gettin(g) somethin(g) to eat here .
cookeiejar@k .
and they're gettin(g) something to eat here .
(.) and this is a nice place <what they>  what
but they put that stuff around in there .
it looks>  &+n it looks nice .
and then here when they had some stuff in through here .
and &-uh +...
I like these things in through here too .
yeah .]
Similar ids = 44
--------
Target text = And there's the picture tell me all the action all the action



okay it's a boy and a girl and their mom and this year 111 their fallen fallen down in through here



and then this year when the water it should be going down in air but it's going down on the side here it's going all the way down in the air



any more action going on or getting something to eat here



see oh okay A I EJAR



and they're getting something to aid here



this is a nice place but they what they what they had what they put that stuff around in there. looks it looks nice. Okay, and then here when they had stopped in through here and said all the action. I like these things in through here too. Good night

-------
Checking item = 143
Checking item = 144
Checking item = 145
Checking item = 146
Checking item = 147
Checking item = 148
Checking item = 149
Checking item = 150
Checking item = 151
New high similarity detected. Index = 60
New high similarity detected. Index = 67
High similarity detected
Src id = 151, file_id = [237-2],
text = [the &-uh young fellow is &+s standing on the step ladder which is
it's a stool which is getting ready to fall .
he's handing>  he's getting a cookie out while he's handing
the top is falling off of the cookie jar .
the girl is standin(g) on the floor with her hand reachin(g) up for
I think she's tellin(g) him to watch it .
he's at the cupboard with the door open .
the mother has her back turned towards them .
the water is overflowing from the faucet into the sink onto the
and she doesn't even hear or know what's going on .
there the cupboard doors are closed .
the window is open or closed and you can see outside .
the path flowers and so forth .
now I know I'm missing something .
she's standing in the water .
(.) <the faucet>  the sink is overflowing .
two cups and a plate are there .
that's all I can see .]
Similar ids = 67
--------

In [36]:
print("Count =", len(result))
print("All similar text pairs:")
for (text1, text2, src_file_id, tgt_file_id) in result:
    print(f"ID={src_file_id}, Source text =", text1[:300])
    print("--------")
    print(f"ID={tgt_file_id}, Target text =", text2[:300])
    print("================================")

Count = 68
All similar text pairs:
ID=029-1, Source text = alright .
I see the little boy stealing cookies from the cookie jar .
and <the little girl's>  &-uh he gave some to the little girl .
and she's eatin(g) some of the cookies .
and I guess this is mama .
and she's washing the dishes .
and she dropped a dish .
no  no ‡ she didn't drop a dish .
uh the
--------
ID=adrsdt20, Target text = All right, tell me what you see going on in that picture. I see the little boy stealing cookies from the cookie jar. And the little girls and he gave some to the little girl and she's eat some of the cookies. And I guess this is mama and she's washing the dishes. And she dropped a dish. No, no, she
================================
ID=030-0, Source text = it's a picture of a kitchen .
there's a child reaching on  a cookie jar .
um <a male>
he's falling .
the stool is falling .
uh his  a female youngster maybe sister is
and she's got a finger to her lip .
the &-uh mother is at the sink washing a dish .
the water is spilling over from the sink .
the wi
--------
ID=adrsdt55, Target text = cute pictures in in a kitchen with a family. Mother and son and daughter and the son is up in the cookie jar. The cupboard doors open he's getting cookies in the jar. He's standing on a stool which is in the process of toppling over the little girls holding her hand for a cookie and she's also has h
================================
ID=049-0, Source text = =clears:throat you want me to tell you ?
um the girl is talking to the boy .
he's getting the cookie jar down .
he has a &+coo cookie in his hand .
uh he's falling off of his stool .
the mother's doing the dishes and the water's running off into the
she's looking out the window apparently .
um I see
--------
ID=adrsdt28, Target text = There's a picture. Let me tell you just tell me everything that you see.



Girls talking to the boy he's getting a cookie jar down. He has a coffee in his hand. He's falling off his stool. Mothers do the dishes and the water is running off into the floor. She's looking out the window apparently. I
================================
ID=058-1, Source text = okay I'll start .
the mother is drying dishes .
and the sink is over flowing .
the water is falling onto the floor .
uh the boy is on his stool &-uh taking cookies out_of a cookie
and he has <one cookie>  two cookies one in each hand .
the &-uh girl is standing, reaching up for a cookie with her &-u
--------
ID=adrsdt43, Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitti
================================
ID=184-1, Source text = okay, I see a boy in the cookie jar .
I see he has the lid off .
I see that he is standing on a three legged stool and he's about to
he has one cookie in his hand, handin(g) it down to his sister and
and I think she's indicating to the boy to keep still so his mother
I see the mother .
uh I guess sh
--------
ID=adrsdt4, Target text = All of the action Okay, I see a boy in a cookie jar as he has a bit off. See, he is standing on a three legged stool and he's about to depart from the two legged stool as one cookies handed down to his sister and she's reaching out for it and I think she's indicating diverting to steal sighs mother

================================
ID=206-0, Source text = well ‡ the mother is drying the plate .
uh the water is running on the floor &+overru overrunning in the
the kids are &+s taking cookies from the cookie jar .
and <on a>
and the girl is receiving the cookies .
the sister „ I suppose .
the little girl .
the little boy is takin(g) the cookies .
and <t
--------
ID=adrsdt18, Target text = What do you see going on infection mother's drying flight or the waters running or running in the Safe Kids taking cookies from the cookie jar and I share that with you know three chests in the cupboard and the girl is receiving the cookies is this guy suppose the little girl and boy is taking the c
================================
ID=212-2, Source text = yeah, alright .
the girl is reaching up for a cookie .
the youngster's getting the cookie out_of the cupboard .
the cookie is in the pan
the &-uh bench  the stool that he's
the door to the cookie cupboard is open .
the lady is washing dishes .
she has a dish cloth in her hand .
the &-uh sink is runn
--------
ID=adrsdt43, Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitti
================================
ID=221-3, Source text = well ‡ the boy is taking cookies out_o(f) the cookie jar .
and he's handing one to his sister as he almost falls off his stool
and he has knocked the lid off the cookie jar .
and the mother is washing dishes .
and she has let the sink overflow .
and she's standing in a puddle .
and &+d window is ope
--------
ID=adrsdt31, Target text = This boy is about to fall off the stool. The mother is washing dishes and the water spilling over on the kitchen floor. The wind is blowing the curtains. The little girl was laughing and her brother who's taking a cookie out of the cookie jar

================================
ID=222-1, Source text = all the action ?
(.) okay ‡ it's a boy and a girl (.) and their mom .
(.) and
(..) and then this here when the  it should
it's goin(g) all the way down in there .
um they're gettin(g) somethin(g) to eat here .
cookeiejar@k .
and they're gettin(g) something to eat here .
(.) and this is a nice place
--------
ID=adrsdt57, Target text = And there's the picture tell me all the action all the action



okay it's a boy and a girl and their mom and this year 111 their fallen fallen down in through here



and then this year when the water it should be going down in air but it's going down on the side here it's going all the way down in
================================
ID=237-2, Source text = the &-uh young fellow is &+s standing on the step ladder which is
it's a stool which is getting ready to fall .
he's handing>  he's getting a cookie out while he's handing
the top is falling off of the cookie jar .
the girl is standin(g) on the floor with her hand reachin(g) up for
I think she's tel
--------
ID=adrsdt68, Target text = Okay the boy is standing on a stool of his building over he's reaching for cookies in the cookie jar and its sister is standing beside him by them reaching up for some of the cookies and the mother is standing right there then washing dishes think the water is running into the sink and the sink is f
================================
ID=282-0, Source text = well ‡ I see the mother washing dishes .
I see the water flowing out over the sink top .
I see the boy on a stool that's about to tilt .
and he's goin(g) to fall .
he's tryin(g) to get into the cookie jar .
the little girl has her hand out for a cookie .
(.) the water's running .
(.) dishes are on t
--------
ID=adrsdt20, Target text = All right, tell me what you see going on in that picture. I see the little boy stealing cookies from the cookie jar. And the little girls and he gave some to the little girl and she's eat some of the cookies. And I guess this is mama and she's washing the dishes. And she dropped a dish. No, no, she
================================
ID=282-2, Source text = I see the little boy reaching up for the cookie jar but he's also
and he's going to be hurt .
the little girl has her hand up for a cookie from the cookie jar
the  we'll call her the mother is doing dishes .
and the water is splashing out_of the sink .
she can look out the window and see the lawn, t
--------
ID=adrsdt6, Target text = Everything that I see going on. Okay, well, little boy is stealing a cookie from the cookie jar. He's also handing a cookie with his left hand to the girl. He's also falling off the stool or the stool is tipping over. A little girl is reaching for the cookie. And at the same time she's picking her n
================================
ID=283-0, Source text = well ‡ a youngster got up on his stool .
and he's tryin(g) to get into the cookie jar .
and the little girl is already waiting for the cookies .
so ‡ she's standing there with her hand out .
oh my .
and mother is very busy .
oy ‡ she forgot to look at the spigots .
they're still open .
and the water
--------
ID=adrsdt9, Target text = Tell me everything that you see going on. Well youngster got up on a stool and he's trying to get into the cookie jar and the little girl is already waiting for the cookie. So she's standing there with her hand duck. Oh, my and mother is very busy already. She forgot to look at this pickets. They're
================================
ID=357-0, Source text = I see &-uh two kids up at the cookie jar, one on a stool the other
cupboard door is opened .
mother's washing the dishes .
the water is running  overflowing the sink .
and &-uh there's two cups and a plate on the counter .
and she's <washing>  holding a plate in her hand .
curtains at the windows .

--------
ID=adrsdt53, Target text = I see going on. Okay the kid on the bench who's got his hand in the cookie jar and he's falling off and sister ones one. His mother is standing in a puddle of water because she didn't turn off the faucet and she's trying to dry a dish to dry her feet instead. The window was open



water sink is ove
================================
ID=497-0, Source text = well the little boy went up to get some cookies .
and the little girl reaching up to give the jar <to the>  &+cook
the mother is washing dishes .
and the>  &-uh the sink is <full of dish(es)>
and the mother is still &-uh &-uh &+w &-uh wiping the dishes .
and let's see what else .
and the boy is &-uh
--------
ID=adrsdt25, Target text = Do you see going on in the picture? Well, the little boy went up to get some cookies.



And the little girl reaching up to give that jar to the, to her brother. The mother was washing dishes. And the end the sink is full of dishes full of water and the mother is wiping the dishes. And let's see wha
================================
ID=578-0, Source text = oh I see a woman drying a dish with a dish towel .
I see water overflowing from the sink .
the faucet is running .
um curtains hanging on the wall .
the window, the picture outside of a pathway and grass and hedges
I see the cabinets below her .
she's wearin(g) shoes dress and apron .
um I see the c
--------
ID=adrsdt43, Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitti
================================
ID=598-0, Source text = well ‡ there's a little boy <on the>  on a stool .
he's gonna fall shortly snitching cookies .
mommy's washin(g) dishes .
and the sink is runnin(g) over .
(..) I don't know if there's anything more there or not but that's
I see a cookie jar .
snitchin(g) cookies .
--------
ID=adrsdt13, Target text = Well, there's a little boy on a on a stool.



He's gonna fall shortly. snitching cookies, mommy's washing dishes



and the sink is running over



I don't know if there's anything more there or not, but that's what I see. I see a cookie jar. Okay, that's fine. niching cookies Okay,

================================
ID=640-0, Source text = the little boy's take  getting in the cookie jar .
his <mom's is>  mom is washing the dishes and dryin(g) them .
oh ‡ somebody let the water run over .
and the little boy is going to get killed if he doesn't get up off
and then there's a little girl .
" I'll take the cookie jar .
--------
ID=adrsdt16, Target text = Little boys take getting in the cookie jar.



His mom's his mom is washing the dishes



drying.



Oh, somebody let the water run over and the little boy is going to get killed and then there's a little girl



take the cookie jar

================================
ID=676-0, Source text = the boy and the girl are playing .
and he's gonna fall down off the ladder  .
and the mother's washing the dishes .
and it's flying out over the sink down to the floor .
what else do you want me to tell you ?
whatever you see happening .
yeah that's it .
--------
ID=adrsdt7, Target text = Everything that you see happening in that picture everything that's going on there. The boy and the girl are playing and he's gonna fold on off the ladder. And mother washing the dishes and flying out over the sink down to the floor. Whatever you want my carrier that's all whatever you see happening
================================
ID=006-3, Source text = well the kids are in the kitchen with their mother &-uh &-uh
a boy's handin(g) it to the girl .
and the boy's &-uh <on a>  on a &-uh stool and he's tripping
he's gonna fall on the floor .
the mother's standing there doing the dishes .
she's washing the dishes looking out the open window .
and the wa
--------
ID=adrsdt31, Target text = This boy is about to fall off the stool. The mother is washing dishes and the water spilling over on the kitchen floor. The wind is blowing the curtains. The little girl was laughing and her brother who's taking a cookie out of the cookie jar

================================
ID=015-4, Source text = okay start ?
okay a little boy is getting a cookie out_of the cookie jar .
he's standing on a stool .
it's tipped over and he's handing <his sister a>
and the little girl is saying ssh because they don't want their
and the mother is wiping a dish .
and she has the water  in her faucet
and she's step
--------
ID=adrsdt43, Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitti
================================
ID=021-2, Source text = mother's washing dishes .
the sink is overflowing .
the boy's falling off a chair  as he's getting for
girl's reaching up for the cookie .
um I did say the water is running down .
the mother's looking out the window .
(.) &-uh dishes of_course are on the sink .
think that's about it .
--------
ID=adrsdt31, Target text = This boy is about to fall off the stool. The mother is washing dishes and the water spilling over on the kitchen floor. The wind is blowing the curtains. The little girl was laughing and her brother who's taking a cookie out of the cookie jar

================================
ID=022-1, Source text = I see a little boy on a stool trying to reach the cookie jar .
he's got one in his hand that to his little sister .
and the stool is falling over tipping .
and <the lady is>  (gue)ss mama is standin(g) by the sink
and the water's running over on the floor .
and outside you can see the walk and the s
--------
ID=adrsdt13, Target text = Well, there's a little boy on a on a stool.



He's gonna fall shortly. snitching cookies, mommy's washing dishes



and the sink is running over



I don't know if there's anything more there or not, but that's what I see. I see a cookie jar. Okay, that's fine. niching cookies Okay,

================================
ID=034-4, Source text = tell you everything that's going on ?
there's a little girl asking her brother for a cookie .
he is on a &+s step>  he's on a high stepstool reaching up high
and the stool is going out from under him .
he is going to fall .
the mother is washing dishes and not paying attention .
the sink>  the water
--------
ID=adrsdt31, Target text = This boy is about to fall off the stool. The mother is washing dishes and the water spilling over on the kitchen floor. The wind is blowing the curtains. The little girl was laughing and her brother who's taking a cookie out of the cookie jar

================================
ID=042-1, Source text = okay .
uh the little boy is on the &-uh stool &-uh which is tipping over
and he's getting into the cookie jar which is up in the cabinet .
uh the lid is off the jar .
he has a cookie in one hand .
he's reaching for another one .
uh the little girl has her hand up for &-uh a cookie I guess to
and one
--------
ID=adrsdt43, Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitti
================================
ID=042-3, Source text = okay &-uh the boy is up in the cupboard &-uh getting cookies and
little girl's reaching up her hand .
she has her finger up to her mouth .
um mother's drying a dish at the sink .
the water is running over onto the floor .
um there's a <cup and>  two cups and a dish on the counter .
uh outside there'
--------
ID=adrsdt43, Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitti
================================
ID=045-2, Source text = what's going on ?
okay .
uh mother's &-uh drying dishes .
sink is overflowing .
son is &-uh falling off a stool .
son is &-uh raiding the cookie jar .
uh sister is &-uh laughing at her brother .
and she's reaching for a cookie .
and &-uh the window is open .
uh <the cup>  two cups and &-uh a dish on
--------
ID=adrsdt68, Target text = Okay the boy is standing on a stool of his building over he's reaching for cookies in the cookie jar and its sister is standing beside him by them reaching up for some of the cookies and the mother is standing right there then washing dishes think the water is running into the sink and the sink is f
================================
ID=045-3, Source text = okay .
uh the child's falling off the chair .
he's taking cookies out o(f) the jar .
the girl is standing on the floor &-uh asking for a cookie .
the door to>  the &+c cabinet door is open .
mother is washing dishes .
the sink is overflowing .
the water's running .
uh I don't know if she's dryin(g)
--------
ID=adrsdt43, Target text = water running out of the sink. Lady drying plate Chow getting cookies out of the cookie jar



standing on a stool tipping over no girl reaching



up for cookie and curtains that we know have outside tree a window into another room shrubbery grass get back to the room again cut two cups plate sitti
================================
ID=052-0, Source text = a boy is taking &-uh cookies from the cookie jar giving one to his
he's also falling off the stool he is on .
the mother is washing dishes .
she's letting the sink overflow .
it's getting all over the floor .
I see nothing further .
(...) the girl is saying be quiet <if that>  if that counts .
I don
--------
ID=adrsdt6, Target text = Everything that I see going on. Okay, well, little boy is stealing a cookie from the cookie jar. He's also handing a cookie with his left hand to the girl. He's also falling off the stool or the stool is tipping over. A little girl is reaching for the cookie. And at the same time she's picking her n
================================
ID=056-3, Source text = okay .
uh the mother is wiping a dish at the sink .
um the water is overflowing from the sink .
a youngster's about to fall off a stool reaching for a cookie jar .
and the little girl is holding up her hand to grab a cookie out_of

In [37]:
# mark on the source (Pitt dataset) which rows is likely to included in the target set (orginal test set)
src_df["possible_overlap"] = src_df["text"].apply(lambda text: 
                                                  1 if (compare(model.encode(text), 
                                                          tgt_vecs, 
                                                          threshold=threshold
                                                        )) 
                                                  else 0
                                                 )
src_df.head()

New high similarity detected. Index = 38
New high similarity detected. Index = 61
New high similarity detected. Index = 66
New high similarity detected. Index = 39
New high similarity detected. Index = 55
New high similarity detected. Index = 43
New high similarity detected. Index = 11
New high similarity detected. Index = 55
New high similarity detected. Index = 1
New high similarity detected. Index = 46
New high similarity detected. Index = 68
New high similarity detected. Index = 44
New high similarity detected. Index = 60
New high similarity detected. Index = 67
New high similarity detected. Index = 38
New high similarity detected. Index = 38
New high similarity detected. Index = 60
New high similarity detected. Index = 46
New high similarity detected. Index = 0
New high similarity detected. Index = 38
New high similarity detected. Index = 58
New high similarity detected. Index = 48
New high similarity detected. Index = 55
New high similarity detected. Index = 21
New high similarity detected. Index = 25
New high similarity detected. Index = 27
New high similarity detected. Index = 68
New high similarity detected. Index = 55
New high similarity detected. Index = 68
New high similarity detected. Index = 21
New high similarity detected. Index = 68
New high similarity detected. Index = 0
New high similarity detected. Index = 36
New high similarity detected. Index = 55
New high similarity detected. Index = 55
New high similarity detected. Index = 67
New high similarity detected. Index = 55
New high similarity detected. Index = 60
New high similarity detected. Index = 60
New high similarity detected. Index = 67
New high similarity detected. Index = 68
New high similarity detected. Index = 38
New high similarity detected. Index = 68
New high similarity detected. Index = 11
New high similarity detected. Index = 38
New high similarity detected. Index = 61
New high similarity detected. Index = 32
New high similarity detected. Index = 54
New high similarity detected. Index = 55
New high similarity detected. Index = 61
New high similarity detected. Index = 55
New high similarity detected. Index = 61
New high similarity detected. Index = 55
New high similarity detected. Index = 55
New high similarity detected. Index = 36
New high similarity detected. Index = 55
New high similarity detected. Index = 46
New high similarity detected. Index = 68
New high similarity detected. Index = 58
New high similarity detected. Index = 60
New high similarity detected. Index = 36
New high similarity detected. Index = 55
New high similarity detected. Index = 29
New high similarity detected. Index = 55
New high similarity detected. Index = 61
New high similarity detected. Index = 1
New high similarity detected. Index = 61
New high similarity detected. Index = 65
New high similarity detected. Index = 67
New high similarity detected. Index = 60
New high similarity detected. Index = 62
New high similarity detected. Index = 0
New high similarity detected. Index = 38
New high similarity detected. Index = 61
New high similarity detected. Index = 67
New high similarity detected. Index = 68
New high similarity detected. Index = 55
New high similarity detected. Index = 55
New high similarity detected. Index = 70
New high similarity detected. Index = 60
New high similarity detected. Index = 61
New high similarity detected. Index = 11
New high similarity detected. Index = 38
New high similarity detected. Index = 65
New high similarity detected. Index = 66
New high similarity detected. Index = 67
New high similarity detected. Index = 1
New high similarity detected. Index = 61
New high similarity detected. Index = 38
New high similarity detected. Index = 51
New high similarity detected. Index = 61
New high similarity detected. Index = 68
New high similarity detected. Index = 55
New high similarity detected. Index = 19
New high similarity detected. Index = 0
New high similarity detected. Index = 8
New high similarity detected. Index = 60
New high similarity detected. Index = 61
New high similarity detected. Index = 68
New high similarity detected. Index = 35
New high similarity detected. Index = 36

,file_id,text,target,possible_overlap
0,001-0,mhm .\nalright .\nthere's &-um a young boy tha...,AD,0
1,001-2,mhm .\nthere's a young boy &-uh going in a coo...,AD,0
2,003-0,here's a cookie jar .\nand the lid is off the ...,AD,0
3,005-0,the boy is slipping off the stool .\nhe's tryi...,AD,0
4,005-2,okay ‡ he's fallin(g) off a chair .\nshe's &-...,AD,0

In [38]:
src_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549 entries, 0 to 548
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   file_id           549 non-null    object
 1   text              549 non-null    object
 2   target            549 non-null    object
 3   possible_overlap  549 non-null    int64
dtypes: int64(1), object(3)
memory usage: 17.3+ KB

In [39]:
# count how many possible items in Pitt dataset is contained in the test set
count = len(src_df.query("possible_overlap == 1"))
print("Count of possible overlaps in test set =", count)

Count of possible overlaps in test set = 68

In [40]:
# export back to the source (train_pitt.csv)
output_write = True

if output_write:
    fname_out = "../data/splits/train_pitt_markedB.csv"
    print("Output to ", fname_out)
    src_df.to_csv(fname_out, index=False)
    print("Completed")

Output to  ../data/splits/train_pitt_markedB.csv
Completed