## 01 - Audio Embeddings 
In this notebook, we will load audio files, convert them to embedding vectors (using mean pooling), and export to json files

In [1]:
# !pip install torch

In [2]:
# !pip install transformers

In [3]:
# !pip install flash-attn

In [4]:
# !pip install librosa

In [5]:
import pandas as pd
import torch
from transformers import Wav2Vec2Model, Wav2Vec2FeatureExtractor
import librosa
import os
import numpy as np

In [6]:
# testing torch
print(torch.cuda.is_available())
print(torch.cuda.current_device())
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

True
0
cuda

In [7]:
paths = ["../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/ad/", 
         "../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/cn/", 
         "../../data/Test Dataset/Diagnosis Testing dataset/diagnosis/test-dist/audio/",
        ]

In [8]:
def get_file_list(path, ext=".wav"):
    """
        get all filenames in a folder
        returns a dictionary {file_id:full_path}
    """
    result = dict()
    # filenames = []
    # get only wav files
    print("Reading from folder =", path)
    files = [item
             for item in os.listdir(path)
             if item.endswith(ext)
            ]
    
    for fname in files:
        result[fname.replace(ext, "")] = path + fname 

    print("Count =", len(result))
    return result

In [9]:
file_paths = [get_file_list(path)
              for path in paths
             ]
print(len(file_paths))
print(len(file_paths[0].keys()))

Reading from folder = ../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/ad/
Count = 87
Reading from folder = ../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/cn/
Count = 79
Reading from folder = ../../data/Test Dataset/Diagnosis Testing dataset/diagnosis/test-dist/audio/
Count = 71
3
87

In [10]:
# merge dictionaries
file_paths_dict = dict()


for fpath in file_paths:
    file_paths_dict.update(fpath)

print(len(file_paths_dict))

237

In [11]:
# create audio processing model
model_name = "facebook/wav2vec2-large-960h-lv60-self"
model = Wav2Vec2Model.from_pretrained(model_name,
                                      torch_dtype=torch.float16,
                                     ).to(device)

C:\Users\Minh UBC\miniconda3\Lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-large-960h-lv60-self and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [12]:
extractor = Wav2Vec2FeatureExtractor.from_pretrained(model_name)

In [13]:
# put into a function
def audio2vec(fname, model=model, extractor=extractor, fl16=True):
    """
        Read a wav file and return mean pooling embeddings (length 512)
    """
    result = []
    print("Loading file =", fname)
    input_audio, sample_rate = librosa.load(fname, sr=16000)

    # convert to float16
    if fl16:
        input_audio = input_audio.astype(np.float16)
        
    print("Completed")
    print("Calculating embeddings...")
    
    result = extractor(input_audio, return_tensors="pt", sampling_rate=sample_rate).to(device)
    with torch.no_grad():
        output = model(result.input_values)

    print("Calculating mean pooling...")

    # result = np.average(output.extract_features[0], axis=0)
    result = torch.mean(output.extract_features[0], dim=0).cpu()
    # debug:
    print("Shape =", result.shape)
    return result

In [14]:
# test loading wav file
# fname = "../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/cn/adrso002.wav"
# path = "../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/"
# fname = "../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/cn/adrso002.wav"  # small file 6 MB
# fname = "../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/ad/adrso024.wav" # bigger file 20 MB
# fname = "../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/ad/adrso192.wav" # bigger file 38 MB

VEC_LEN = 512

fname = file_paths_dict["adrso002"] # small file 
print(fname)

result = audio2vec(fname)
assert len(result) == VEC_LEN
print("All passed")

../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/cn/adrso002.wav
Loading file = ../../data/Transcribed Data-2024-Feb-13/Diagnosis Training Data/cn/adrso002.wav
Completed
Calculating embeddings...
Calculating mean pooling...
Shape = torch.Size([512])
All passed

In [15]:
# load previous embed, will skip already processed items
path_out = "../../data/audio_embed/"
fname_existing = "train_audio_embed.json"

try:
    existing_df = pd.read_json(path_out + fname_existing,
                              orient="records")
except Exception as e:
    print("Error reading file =", fname_existing)
    existing_df = pd.DataFrame({"file_id":[], 
                                "audio_embed":[]
                               })
print(len(existing_df))
existing_df.head()

237

    file_id                                        audio_embed
0  adrsdt26  [0.572265625, 0.0052719116, 0.1276855469, 0.04...
1  adrsdt32  [0.4912109375, -0.3137207031, 0.4453125, -0.19...
2  adrsdt37  [0.5161132812, -0.2147216797, 0.3342285156, 0....
3  adrsdt44  [0.3947753906, 0.0309295654, 1.111328125, 0.22...
4  adrsdt46  [0.3186035156, -0.2010498047, -0.1440429688, -...

In [16]:
# check existing file
fid = "adrso024"
print(sum(existing_df["file_id"].str.contains(fid)))
print(fid in list(existing_df["file_id"]))
print(existing_df.query("file_id == @fid").iloc[0]["audio_embed"][:10]) # check existing value

1
True
[0.0742797852, -0.2470703125, -0.2939453125, -0.1875, 0.5258789062, 0.6860351562, -0.1779785156, -0.0234375, -0.2900390625, -0.1143188477]

In [17]:
# calculate embeddings for list of files
embed_data = dict()
n = len(file_paths_dict.items())
print("N =", n)

max_n = n # set to n for full set

fnames = list(file_paths_dict.keys())
for i, fname in enumerate(fnames[:max_n]):
    print(f"Processing {i+1}/{max_n} = {(i+1)*100/max_n:.0f} %, file name = {fname}")
    if fname in list(existing_df["file_id"]):
        print("File existed. Skipping...")
        # embed_data[fname] = existing_df.query("file_id == @fid")["audio_embed"][0] # copy over from existing dataframe
        continue
    
    v = audio2vec(file_paths_dict[fname])
    embed_data[fname] = v
    print("---------------")

print("All Completed")

N = 237
Processing 1/237 = 0 %, file name = adrso024
File existed. Skipping...
Processing 2/237 = 1 %, file name = adrso025
File existed. Skipping...
Processing 3/237 = 1 %, file name = adrso027
File existed. Skipping...
Processing 4/237 = 2 %, file name = adrso028
File existed. Skipping...
Processing 5/237 = 2 %, file name = adrso031
File existed. Skipping...
Processing 6/237 = 3 %, file name = adrso032
File existed. Skipping...
Processing 7/237 = 3 %, file name = adrso033
File existed. Skipping...
Processing 8/237 = 3 %, file name = adrso035
File existed. Skipping...
Processing 9/237 = 4 %, file name = adrso036
File existed. Skipping...
Processing 10/237 = 4 %, file name = adrso039
File existed. Skipping...
Processing 11/237 = 5 %, file name = adrso043
File existed. Skipping...
Processing 12/237 = 5 %, file name = adrso045
File existed. Skipping...
Processing 13/237 = 5 %, file name = adrso046
File existed. Skipping...
Processing 14/237 = 6 %, file name = adrso047
File existed. Skipping...
Processing 15/237 = 6 %, file name = adrso049
File existed. Skipping...
Processing 16/237 = 7 %, file name = adrso053
File existed. Skipping...
Processing 17/237 = 7 %, file name = adrso054
File existed. Skipping...
Processing 18/237 = 8 %, file name = adrso055
File existed. Skipping...
Processing 19/237 = 8 %, file name = adrso056
File existed. Skipping...
Processing 20/237 = 8 %, file name = adrso059
File existed. Skipping...
Processing 21/237 = 9 %, file name = adrso060
File existed. Skipping...
Processing 22/237 = 9 %, file name = adrso063
File existed. Skipping...
Processing 23/237 = 10 %, file name = adrso068
File existed. Skipping...
Processing 24/237 = 10 %, file name = adrso070
File existed. Skipping...
Processing 25/237 = 11 %, file name = adrso071
File existed. Skipping...
Processing 26/237 = 11 %, file name = adrso072
File existed. Skipping...
Processing 27/237 = 11 %, file name = adrso074
File existed. Skipping...
Processing 28/237 = 12 %, file name = adrso075
File existed. Skipping...
Processing 29/237 = 12 %, file name = adrso077
File existed. Skipping...
Processing 30/237 = 13 %, file name = adrso078
File existed. Skipping...
Processing 31/237 = 13 %, file name = adrso089
File existed. Skipping...
Processing 32/237 = 14 %, file name = adrso090
File existed. Skipping...
Processing 33/237 = 14 %, file name = adrso092
File existed. Skipping...
Processing 34/237 = 14 %, file name = adrso093
File existed. Skipping...
Processing 35/237 = 15 %, file name = adrso098
File existed. Skipping...
Processing 36/237 = 15 %, file name = adrso106
File existed. Skipping...
Processing 37/237 = 16 %, file name = adrso109
File existed. Skipping...
Processing 38/237 = 16 %, file name = adrso110
File existed. Skipping...
Processing 39/237 = 16 %, file name = adrso112
File existed. Skipping...
Processing 40/237 = 17 %, file name = adrso116
File existed. Skipping...
Processing 41/237 = 17 %, file name = adrso122
File existed. Skipping...
Processing 42/237 = 18 %, file name = adrso123
File existed. Skipping...
Processing 43/237 = 18 %, file name = adrso125
File existed. Skipping...
Processing 44/237 = 19 %, file name = adrso126
File existed. Skipping...
Processing 45/237 = 19 %, file name = adrso128
File existed. Skipping...
Processing 46/237 = 19 %, file name = adrso130
File existed. Skipping...
Processing 47/237 = 20 %, file name = adrso134
File existed. Skipping...
Processing 48/237 = 20 %, file name = adrso138
File existed. Skipping...
Processing 49/237 = 21 %, file name = adrso141
File existed. Skipping...
Processing 50/237 = 21 %, file name = adrso142
File existed. Skipping...
Processing 51/237 = 22 %, file name = adrso144
File existed. Skipping...
Processing 52/237 = 22 %, file name = adrso187
File existed. Skipping...
Processing 53/237 = 22 %, file name = adrso188
File existed. Skipping...
Processing 54/237 = 23 %, file name = adrso189
File existed. Skipping...
Processing 55/237 = 23 %, file name = adrso190
File existed. Skipping...
Processing 56/237 = 24 %, file name = adrso192
File existed. Skipping...
Processing 57/237 = 24 %, file name = adrso197
File existed. Skipping...
Processing 58/237 = 24 %, file name = adrso198
File existed. Skipping...
Processing 59/237 = 25 %, file name = adrso200
File existed. Skipping...
Processing 60/237 = 25 %, file name = adrso202
File existed. Skipping...
Processing 61/237 = 26 %, file name = adrso205
File existed. Skipping...
Processing 62/237 = 26 %, file name = adrso206
File existed. Skipping...
Processing 63/237 = 27 %, file name = adrso209
File existed. Skipping...
Processing 64/237 = 27 %, file name = adrso211
File existed. Skipping...
Processing 65/237 = 27 %, file name = adrso212
File existed. Skipping...
Processing 66/237 = 28 %, file name = adrso215
File existed. Skipping...
Processing 67/237 = 28 %, file name = adrso216
File existed. Skipping...
Processing 68/237 = 29 %, file name = adrso218
File existed. Skipping...
Processing 69/237 = 29 %, file name = adrso220
File existed. Skipping...
Processing 70/237 = 30 %, file name = adrso222
File existed. Skipping...
Processing 71/237 = 30 %, file name = adrso223
File existed. Skipping...
Processing 72/237 = 30 %, file name = adrso224
File existed. Skipping...
Processing 73/237 = 31 %, file name = adrso228
File existed. Skipping...
Processing 74/237 = 31 %, file name = adrso229
File existed. Skipping...
Processing 75/237 = 32 %, file name = adrso232
File existed. Skipping...
Processing 76/237 = 32 %, file name = adrso233
File existed. Skipping...
Processing 77/237 = 32 %, file name = adrso234
File existed. Skipping...
Processing 78/237 = 33 %, file name = adrso236
File existed. Skipping...
Processing 79/237 = 33 %, file name = adrso237
File existed. Skipping...
Processing 80/237 = 34 %, file name = adrso244
File existed. Skipping...
Processing 81/237 = 34 %, file name = adrso245
File existed. Skipping...
Processing 82/237 = 35 %, file name = adrso246
File existed. Skipping...
Processing 83/237 = 35 %, file name = adrso247
File existed. Skipping...
Processing 84/237 = 35 %, file name = adrso248
File existed. Skipping...
Processing 85/237 = 36 %, file name = adrso249
File existed. Skipping...
Processing 86/237 = 36 %, file name = adrso250
File existed. Skipping...
Processing 87/237 = 37 %, file name = adrso253
File existed. Skipping...
Processing 88/237 = 37 %, file name = adrso002
File existed. Skipping...
Processing 89/237 = 38 %, file name = adrso003
File existed. Skipping...
Processing 90/237 = 38 %, file name = adrso005
File existed. Skipping...
Processing 91/237 = 38 %, file name = adrso007
File existed. Skipping...
Processing 92/237 = 39 %, file name = adrso008
File existed. Skipping...
Processing 93/237 = 39 %, file name = adrso010
File existed. Skipping...
Processing 94/237 = 40 %, file name = adrso012
File existed. Skipping...
Processing 95/237 = 40 %, file name = adrso014
File existed. Skipping...
Processing 96/237 = 41 %, file name = adrso015
File existed. Skipping...
Processing 97/237 = 41 %, file name = adrso016
File existed. Skipping...
Processing 98/237 = 41 %, file name = adrso017
File existed. Skipping...
Processing 99/237 = 42 %, file name = adrso018
File existed. Skipping...
Processing 100/237 = 42 %, file name = adrso019
File existed. Skipping...
Processing 101/237 = 43 %, file name = adrso021
File existed. Skipping...
Processing 102/237 = 43 %, file name = adrso022
File existed. Skipping...
Processing 103/237 = 43 %, file name = adrso023
File existed. Skipping...
Processing 104/237 = 44 %, file name = adrso148
File existed. Skipping...
Processing 105/237 = 44 %, file name = adrso151
File existed. Skipping...
Processing 106/237 = 45 %, file name = adrso152
File existed. Skipping...
Processing 107/237 = 45 %, file name = adrso153
File existed. Skipping...
Processing 108/237 = 46 %, file name = adrso154
File existed. Skipping...
Processing 109/237 = 46 %, file name = adrso156
File existed. Skipping...
Processing 110/237 = 46 %, file name = adrso157
File existed. Skipping...
Processing 111/237 = 47 %, file name = adrso158
File existed. Skipping...
Processing 112/237 = 47 %, file name = adrso159
File existed. Skipping...
Processing 113/237 = 48 %, file name = adrso160
File existed. Skipping...
Processing 114/237 = 48 %, file name = adrso161
File existed. Skipping...
Processing 115/237 = 49 %, file name = adrso162
File existed. Skipping...
Processing 116/237 = 49 %, file name = adrso164
File existed. Skipping...
Processing 117/237 = 49 %, file name = adrso165
File existed. Skipping...
Processing 118/237 = 50 %, file name = adrso167
File existed. Skipping...
Processing 119/237 = 50 %, file name = adrso168
File existed. Skipping...
Processing 120/237 = 51 %, file name = adrso169
File existed. Skipping...
Processing 121/237 = 51 %, file name = adrso170
File existed. Skipping...
Processing 122/237 = 51 %, file name = adrso172
File existed. Skipping...
Processing 123/237 = 52 %, file name = adrso173
File existed. Skipping...
Processing 124/237 = 52 %, file name = adrso177
File existed. Skipping...
Processing 125/237 = 53 %, file name = adrso178
File existed. Skipping...
Processing 126/237 = 53 %, file name = adrso180
File existed. Skipping...
Processing 127/237 = 54 %, file name = adrso182
File existed. Skipping...
Processing 128/237 = 54 %, file name = adrso183
File existed. Skipping...
Processing 129/237 = 54 %, file name = adrso186
File existed. Skipping...
Processing 130/237 = 55 %, file name = adrso257
File existed. Skipping...
Processing 131/237 = 55 %, file name = adrso259
File existed. Skipping...
Processing 132/237 = 56 %, file name = adrso260
File existed. Skipping...
Processing 133/237 = 56 %, file name = adrso261
File existed. Skipping...
Processing 134/237 = 57 %, file name = adrso262
File existed. Skipping...
Processing 135/237 = 57 %, file name = adrso263
File existed. Skipping...
Processing 136/237 = 57 %, file name = adrso264
File existed. Skipping...
Processing 137/237 = 58 %, file name = adrso265
File existed. Skipping...
Processing 138/237 = 58 %, file name = adrso266
File existed. Skipping...
Processing 139/237 = 59 %, file name = adrso267
File existed. Skipping...
Processing 140/237 = 59 %, file name = adrso268
File existed. Skipping...
Processing 141/237 = 59 %, file name = adrso270
File existed. Skipping...
Processing 142/237 = 60 %, file name = adrso273
File existed. Skipping...
Processing 143/237 = 60 %, file name = adrso274
File existed. Skipping...
Processing 144/237 = 61 %, file name = adrso276
File existed. Skipping...
Processing 145/237 = 61 %, file name = adrso277
File existed. Skipping...
Processing 146/237 = 62 %, file name = adrso278
File existed. Skipping...
Processing 147/237 = 62 %, file name = adrso280
File existed. Skipping...
Processing 148/237 = 62 %, file name = adrso281
File existed. Skipping...
Processing 149/237 = 63 %, file name = adrso283
File existed. Skipping...
Processing 150/237 = 63 %, file name = adrso285
File existed. Skipping...
Processing 151/237 = 64 %, file name = adrso286
File existed. Skipping...
Processing 152/237 = 64 %, file name = adrso289
File existed. Skipping...
Processing 153/237 = 65 %, file name = adrso291
File existed. Skipping...
Processing 154/237 = 65 %, file name = adrso292
File existed. Skipping...
Processing 155/237 = 65 %, file name = adrso296
File existed. Skipping...
Processing 156/237 = 66 %, file name = adrso298
File existed. Skipping...
Processing 157/237 = 66 %, file name = adrso299
File existed. Skipping...
Processing 158/237 = 67 %, file name = adrso300
File existed. Skipping...
Processing 159/237 = 67 %, file name = adrso302
File existed. Skipping...
Processing 160/237 = 68 %, file name = adrso307
File existed. Skipping...
Processing 161/237 = 68 %, file name = adrso308
File existed. Skipping...
Processing 162/237 = 68 %, file name = adrso309
File existed. Skipping...
Processing 163/237 = 69 %, file name = adrso310
File existed. Skipping...
Processing 164/237 = 69 %, file name = adrso312
File existed. Skipping...
Processing 165/237 = 70 %, file name = adrso315
File existed. Skipping...
Processing 166/237 = 70 %, file name = adrso316
File existed. Skipping...
Processing 167/237 = 70 %, file name = adrsdt1
File existed. Skipping...
Processing 168/237 = 71 %, file name = adrsdt10
File existed. Skipping...
Processing 169/237 = 71 %, file name = adrsdt11
File existed. Skipping...
Processing 170/237 = 72 %, file name = adrsdt12
File existed. Skipping...
Processing 171/237 = 72 %, file name = adrsdt13
File existed. Skipping...
Processing 172/237 = 73 %, file name = adrsdt14
File existed. Skipping...
Processing 173/237 = 73 %, file name = adrsdt15
File existed. Skipping...
Processing 174/237 = 73 %, file name = adrsdt16
File existed. Skipping...
Processing 175/237 = 74 %, file name = adrsdt17
File existed. Skipping...
Processing 176/237 = 74 %, file name = adrsdt18
File existed. Skipping...
Processing 177/237 = 75 %, file name = adrsdt19
File existed. Skipping...
Processing 178/237 = 75 %, file name = adrsdt2
File existed. Skipping...
Processing 179/237 = 76 %, file name = adrsdt20
File existed. Skipping...
Processing 180/237 = 76 %, file name = adrsdt21
File existed. Skipping...
Processing 181/237 = 76 %, file name = adrsdt22
File existed. Skipping...
Processing 182/237 = 77 %, file name = adrsdt23
File existed. Skipping...
Processing 183/237 = 77 %, file name = adrsdt24
File existed. Skipping...
Processing 184/237 = 78 %, file name = adrsdt25
File existed. Skipping...
Processing 185/237 = 78 %, file name = adrsdt26
File existed. Skipping...
Processing 186/237 = 78 %, file name = adrsdt27
File existed. Skipping...
Processing 187/237 = 79 %, file name = adrsdt28
File existed. Skipping...
Processing 188/237 = 79 %, file name = adrsdt29
File existed. Skipping...
Processing 189/237 = 80 %, file name = adrsdt3
File existed. Skipping...
Processing 190/237 = 80 %, file name = adrsdt30
File existed. Skipping...
Processing 191/237 = 81 %, file name = adrsdt31
File existed. Skipping...
Processing 192/237 = 81 %, file name = adrsdt32
File existed. Skipping...
Processing 193/237 = 81 %, file name = adrsdt33
File existed. Skipping...
Processing 194/237 = 82 %, file name = adrsdt34
File existed. Skipping...
Processing 195/237 = 82 %, file name = adrsdt35
File existed. Skipping...
Processing 196/237 = 83 %, file name = adrsdt36
File existed. Skipping...
Processing 197/237 = 83 %, file name = adrsdt37
File existed. Skipping...
Processing 198/237 = 84 %, file name = adrsdt38
File existed. Skipping...
Processing 199/237 = 84 %, file name = adrsdt39
File existed. Skipping...
Processing 200/237 = 84 %, file name = adrsdt4
File existed. Skipping...
Processing 201/237 = 85 %, file name = adrsdt40
File existed. Skipping...
Processing 202/237 = 85 %, file name = adrsdt41
File existed. Skipping...
Processing 203/237 = 86 %, file name = adrsdt42
File existed. Skipping...
Processing 204/237 = 86 %, file name = adrsdt43
File existed. Skipping...
Processing 205/237 = 86 %, file name = adrsdt44
File existed. Skipping...
Processing 206/237 = 87 %, file name = adrsdt45
File existed. Skipping...
Processing 207/237 = 87 %, file name = adrsdt46
File existed. Skipping...
Processing 208/237 = 88 %, file name = adrsdt47
File existed. Skipping...
Processing 209/237 = 88 %, file name = adrsdt48
File existed. Skipping...
Processing 210/237 = 89 %, file name = adrsdt49
File existed. Skipping...
Processing 211/237 = 89 %, file name = adrsdt5
File existed. Skipping...
Processing 212/237 = 89 %, file name = adrsdt50
File existed. Skipping...
Processing 213/237 = 90 %, file name = adrsdt51
File existed. Skipping...
Processing 214/237 = 90 %, file name = adrsdt52
File existed. Skipping...
Processing 215/237 = 91 %, file name = adrsdt53
File existed. Skipping...
Processing 216/237 = 91 %, file name = adrsdt54
File existed. Skipping...
Processing 217/237 = 92 %, file name = adrsdt55
File existed. Skipping...
Processing 218/237 = 92 %, file name = adrsdt56
File existed. Skipping...
Processing 219/237 = 92 %, file name = adrsdt57
File existed. Skipping...
Processing 220/237 = 93 %, file name = adrsdt58
File existed. Skipping...
Processing 221/237 = 93 %, file name = adrsdt59
File existed. Skipping...
Processing 222/237 = 94 %, file name = adrsdt6
File existed. Skipping...
Processing 223/237 = 94 %, file name = adrsdt60
File existed. Skipping...
Processing 224/237 = 95 %, file name = adrsdt61
File existed. Skipping...
Processing 225/237 = 95 %, file name = adrsdt62
File existed. Skipping...
Processing 226/237 = 95 %, file name = adrsdt63
File existed. Skipping...
Processing 227/237 = 96 %, file name = adrsdt64
File existed. Skipping...
Processing 228/237 = 96 %, file name = adrsdt65
File existed. Skipping...
Processing 229/237 = 97 %, file name = adrsdt66
File existed. Skipping...
Processing 230/237 = 97 %, file name = adrsdt67
File existed. Skipping...
Processing 231/237 = 97 %, file name = adrsdt68
File existed. Skipping...
Processing 232/237 = 98 %, file name = adrsdt69
File existed. Skipping...
Processing 233/237 = 98 %, file name = adrsdt7
File existed. Skipping...
Processing 234/237 = 99 %, file name = adrsdt70
File existed. Skipping...
Processing 235/237 = 99 %, file name = adrsdt71
File existed. Skipping...
Processing 236/237 = 100 %, file name = adrsdt8
File existed. Skipping...
Processing 237/237 = 100 %, file name = adrsdt9
File existed. Skipping...
All Completed

In [18]:
# print("Count =", len(embed_data))
# print("Element shape =", embed_data[fnames[0]].shape)

In [19]:
f_get_embed = lambda fid: (np.asarray(embed_data[fid].cpu().numpy()) 
                           # if fid in embed_data.keys()
                           # else existing_df.query("file_id==@fid")["audio_embed"][0]
                          )

In [20]:
# convert to dataframe

df_out = pd.DataFrame({"file_id": list(embed_data.keys())})
# df_out["audio_embed"] = df_out["file_id"].apply(lambda fid: np.asarray(embed_data.[fid].cpu().numpy()))
# df_out["audio_embed"] = df_out["file_id"].apply(lambda fid: list(torch.asarray(embed_data[fid])))
df_out["audio_embed"] = df_out["file_id"].apply(f_get_embed)

df_out.head()

Empty DataFrame
Columns: [file_id, audio_embed]
Index: []

In [21]:
print(len(df_out))

0

In [22]:
# copy existing data over
df_out = pd.concat([df_out, existing_df], ignore_index=True)
print(len(df_out))

237

In [23]:
# check type
print(type(df_out.iloc[0]["audio_embed"]))
print(type(df_out.iloc[0]["audio_embed"][0]))

<class 'list'>
<class 'float'>

In [24]:
# write to json file
path_out = "../../data/audio_embed/"
fname_out = "train_audio_embed.json"

print("Writing to file =", fname_out)
df_out.to_json(path_out + fname_out,
               orient="records"
              )
print("Completed")

Writing to file = train_audio_embed.json
Completed